apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "Chart.fullname" . }}
  labels:
    {{- include "Chart.labels" . | nindent 4 }}
spec:
  gateways:
  - {{ include "Chart.fullname" . }}
  hosts:
  - '*'
  http:
  - match:
    - uri:
        exact: /scooter
    route:
    - destination:
        host: scooter
        port:
          number: 80
